[profile.default]
src   = "contracts"
out   = "out"
libs  = ["lib"]
# EXPLICITLY DEFINE REMAPPINGS
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
auto_detect_remappings = false

# Enable the Solidity optimizer to reduce contract size and gas costs
optimizer = true
optimizer_runs = 200000
via_ir = true

[invariant]
maxRuns = 50   # default is 2000 - fart emoji

[fuzz]
runs = 256        # default for fuzz tests
