# foundry.toml

[profile.default]
src   = "contracts"
out   = "out"
libs  = ["lib"]
solc_version = "0.8.24"
# --- FIX: Add trailing slashes to all remapping paths ---
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts/contracts-upgradeable/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
auto_detect_remappings = false
optimizer = true
optimizer_runs = 200000
via_ir = true

[profile.coverage]
optimizer = false
via_ir = false

[invariant]
maxRuns = 50   # default is 2000 - fart emoji

[fuzz]
runs = 256        # default for fuzz tests
