[profile.default]
src   = "contracts"
out   = "out"
libs  = ["lib"]
# ADD THESE LINES TO EXPLICITLY DEFINE REMAPPINGS
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
auto_detect_remappings = false

[invariant]
maxRuns = 50   # default is 2000 - fart emoji

[fuzz]
runs = 256        # default for fuzz tests
