scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['backend:8000']
  - job_name: celery
    static_configs:
      - targets: ['worker:9100']
  - job_name: relay
    static_configs:
      - targets: ['relay:9300']
