// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./Verifier.sol";

/// @title Quadratic Voting proof verifier
/// @dev Extends the autogenerated Verifier contract for QV proofs
contract QVVerifier is Verifier {}
