name: Changelog
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: .github/changelog-config.json
      - name: Commit Changelog
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes"
          git push
