name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Init Git submodules
        run: git submodule update --init --recursive

      - name: Run Solidity unit tests
        run: forge test

      - name: Generate gas report
        run: forge test --gas-report > gas-report.txt

      - name: Upload gas report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: yarn --cwd packages/frontend install

      - name: Type-check frontend
        run: yarn --cwd packages/frontend type-check

      - name: Compile Circom circuits
        run: npx circom circuits/eligibility.circom --r1cs --wasm --sym
