# .github/workflows/ci.yml
name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run unit tests
        run: forge test

      - name: Generate gas report
        run: forge test --gas-report > gas-report.txt

      - name: Upload gas report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm i -g yarn

      - name: Type‑check frontend
        run: yarn install --immutable && yarn --cwd packages/frontend type-check

      - name: Compile Circom circuits
        run: npx circom circuits/eligibility.circom --r1cs --wasm --sym
