name: Manifest-drift
on:
  pull_request:
    paths:
      - 'circuits/**'
      - 'scripts/build_manifest.py'
      - 'artifacts/manifest.json'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Check manifest
        run: |
          for curve in bn254 bls12-381; do
            CURVE=$curve python scripts/build_manifest.py --dry-run
          done
