name: Manifest-drift
on:
  pull_request:
    paths:
      - 'circuits/**'
      - 'scripts/build_manifest.py'
      - 'artifacts/manifest.json'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check manifest
        run: |
          make circuits
      - name: Check verifier
        run: scripts/check_verifier.sh
