name: Preview
on:
  pull_request:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        run: docker compose build
      - name: Start services
        run: docker compose up -d
      - name: Wait for frontend
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Frontend ready" && break
            fi
            sleep 5
          done
      - name: Post preview URL
        uses: actions/deployment@v2
        with:
          token: ${{ github.token }}
          environment: preview
          environment_url: http://localhost:3000
          description: Preview for PR #${{ github.event.pull_request.number }}
      - name: Shutdown services
        if: always()
        run: docker compose down
