# .github/workflows/security-scan.yml
name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Audit Python dependencies
        run: pip-audit -r packages/backend/requirements.txt

      - name: Install frontend dependencies
        run: npm install
        working-directory: packages/frontend

      - name: Audit Node dependencies
        run: npm audit --audit-level=high
        working-directory: packages/frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build orchestrator

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Run Trivy scan
        run: ./scripts/scan-trivy.sh toting-orchestrator
        continue-on-error: true
