name: Solana-tests
on: [push, pull_request]
jobs:
  solana:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout code + submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Anchor and Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cache/anchor
          key: ${{ runner.os }}-anchor-${{ hashFiles('**/Anchor.toml') }}
          restore-keys: |
            ${{ runner.os }}-anchor-

      # 2) install Node, Solana CLI & Anchor CLI
      - uses: metaDAOproject/setup-anchor@v3.1
        with:
          node-version:       '22'
          solana-cli-version: '1.18.18'
          anchor-version:     '0.30.1'

      # 3) run anchor in the election folder
      - name: Show Anchor version
        run: anchor --version
        working-directory: solana-programs/election

      - name: Build & test Solana program
        run: anchor test -- --features skip-entrypoint
        working-directory: solana-programs/election
