name: Fetch Voice Keys

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/fetch_voice_keys.sh'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run fetch script
        run: scripts/fetch_voice_keys.sh
